# This workflow will build and push a new frontend container image to Openshift
name: Remix App Build and Push (Dev)

on:
  push:
    branches: [main]
    paths:
      - './**'
  workflow_dispatch:

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest
    name: remix-app build
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: 'Build Remix App'
        working-directory: './'
        run: |
          pwd
          docker build -t myremixapp:1.3 .
          docker images
          docker image tag myremixapp:1.3 arlopez/myremixapp:1.3

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v2
        with:
          username: arlopez
          password: ${{ secrets.ARLOPEZ }}

      - name: 'Push image'
        run: |
          docker image push arlopez/myremixapp:1.3
